// 倾向数据
export const _rivenDataBaseWeapons = [
  // 步枪 Rifle
  ["Flux Rifle", "Rifle", 1.55],
  ["Harpak", "Rifle", 1.55],
  ["Miter", "Rifle", 1.55],
  ["Mutalist Quanta", "Rifle", 1.55],
  ["Tetra", "Rifle", 1.5],
  ["Deth Machine Rifle", "Rifle", 1.455],
  ["Buzlok", "Rifle", 1.45],
  ["Hind", "Rifle", 1.42],
  ["Attica", "Rifle", 1.415],
  ["Gorgon", "Rifle", 1.4],
  ["Panthera", "Rifle", 1.4],
  ["Vulkar", "Rifle", 1.4],
  ["Glaxion", "Rifle", 1.35],
  ["Mutalist Cernos", "Rifle", 1.35],
  ["Paracyst", "Rifle", 1.315],
  ["Stinger", "Rifle", 1.315],
  ["Synapse", "Rifle", 1.315],
  ["Burston", "Rifle", 1.3],
  ["Daikyu", "Rifle", 1.3],
  ["Dera", "Rifle", 1.3],
  ["Ogris", "Rifle", 1.3],
  ["Penta", "Rifle", 1.3],
  ["Torid", "Rifle", 1.3],
  ["Karak", "Rifle", 1.28],
  ["Latron", "Rifle", 1.25],
  ["Quartakk", "Rifle", 1.25],
  ["Snipetron", "Rifle", 1.25],
  ["Zhuge", "Rifle", 1.25],
  ["Grinlok", "Rifle", 1.245],
  ["Vulklok", "Rifle", 1.245],
  ["Laser Rifle", "Rifle", 1.21],
  ["Argonak", "Rifle", 1.2],
  ["Grakata", "Rifle", 1.2],
  ["Hema", "Rifle", 1.2],
  ["Javlok", "Rifle", 1.2],
  ["Paris", "Rifle", 1.2],
  ["Veldt", "Rifle", 1.2],
  ["Ferrox", "Rifle", 1.15],
  ["Opticor", "Rifle", 1.15],
  ["Scourge", "Rifle", 1.15],
  ["Stradavar", "Rifle", 1.15],
  ["Zarr", "Rifle", 1.15],
  ["Braton", "Rifle", 1.1],
  ["Cernos", "Rifle", 1.1],
  ["Dread", "Rifle", 1.1],
  ["Quanta", "Rifle", 1.1],
  ["Tiberon", "Rifle", 1.1],
  ["Zenith", "Rifle", 1.1],
  ["Nagantaka", "Rifle", 1.05],
  ["Tenora", "Rifle", 1.05],
  ["Artax", "Rifle", 1],
  ["Battacor", "Rifle", 1],
  ["Baza", "Rifle", 1],
  ["Cryotra", "Rifle", 1],
  ["Multron", "Rifle", 1],
  ["Sybaris", "Rifle", 1],
  ["Tazicor", "Rifle", 1],
  ["Vulcax", "Rifle", 1],
  ["Boltor", "Rifle", 0.95],
  ["Tonkor", "Rifle", 0.95],
  ["Lenz", "Rifle", 0.9],
  ["Lanka", "Rifle", 0.85],
  ["Simulor", "Rifle", 0.85],
  ["Supra", "Rifle", 0.85],
  ["Vectis", "Rifle", 0.85],
  ["Rubico", "Rifle", 0.8],
  ["Soma", "Rifle", 0.75],
  ["Amprex", "Rifle", 0.7],
  ["Ignis", "Rifle", 0.6],

  // 霰弹枪 Shotgun
  ["Drakgoon", "Shotgun", 1.48],
  ["Convectrix", "Shotgun", 1.46],
  ["Phage", "Shotgun", 1.46],
  ["Kohm", "Shotgun", 1.4],
  ["Strun", "Shotgun", 1.35],
  ["Boar", "Shotgun", 1.34],
  ["Sobek", "Shotgun", 1.33],
  ["Astilla", "Shotgun", 1.1],
  ["Exergis", "Shotgun", 1],
  ["Phantasma", "Shotgun", 1],
  ["Sweeper", "Shotgun", 1],
  ["Corinth", "Shotgun", 0.95],
  ["Hek", "Shotgun", 0.85],
  ["Arca Plasmor", "Shotgun", 0.6],
  ["Tigris", "Shotgun", 0.5],

  // 手枪 Pistol
  ["Kraken", "Pistol", 1.53],
  ["Magnus", "Pistol", 1.53],
  ["Aklato", "Pistol", 1.52],
  ["Akzani", "Pistol", 1.52],
  ["Cestra", "Pistol", 1.52],
  ["Bolto", "Pistol", 1.51],
  ["Kunai", "Pistol", 1.51],
  ["Tysis", "Pistol", 1.51],
  ["Seer", "Pistol", 1.5],
  ["Spectra", "Pistol", 1.49],
  ["Stug", "Pistol", 1.48],
  ["Burst Laser", "Pistol", 1.45],
  ["Embolist", "Pistol", 1.45],
  ["Nukor", "Pistol", 1.45],
  ["Viper", "Pistol", 1.45],
  ["Talons", "Pistol", 1.44],
  ["Twin Vipers", "Pistol", 1.41],
  ["Afuris", "Pistol", 1.39],
  ["Bronco", "Pistol", 1.35],
  ["Castanas", "Pistol", 1.35],
  ["Furis", "Pistol", 1.35],
  ["Kohmak", "Pistol", 1.35],
  ["Lato", "Pistol", 1.35],
  ["Vasto", "Pistol", 1.35],
  ["Acrid", "Pistol", 1.33],
  ["Angstrum", "Pistol", 1.3],
  ["Despair", "Pistol", 1.3],
  ["Dual Cestra", "Pistol", 1.3],
  ["Dual Toxocyst", "Pistol", 1.3],
  ["Fusilai", "Pistol", 1.3],
  ["Stubba", "Pistol", 1.3],
  ["Twin Gremlins", "Pistol", 1.3],
  ["Akmagnus", "Pistol", 1.28],
  ["Akbronco", "Pistol", 1.25],
  ["Akjagara", "Pistol", 1.25],
  ["Azima", "Pistol", 1.25],
  ["Kulstar", "Pistol", 1.25],
  ["Twin Kohmak", "Pistol", 1.25],
  ["Aksomati", "Pistol", 1.2],
  ["Akvasto", "Pistol", 1.2],
  ["Twin Rogga", "Pistol", 1.2],
  ["Zakti", "Pistol", 1.2],
  ["Knell", "Pistol", 1.15],
  ["Sicarus", "Pistol", 1.15],
  ["Zylok", "Pistol", 1.15],
  ["Brakk", "Pistol", 1.1],
  ["Cycron", "Pistol", 1.1],
  ["Hystrix", "Pistol", 1.1],
  ["Ocucor", "Pistol", 1.1],
  ["Plinx", "Pistol", 1.1],
  ["Ballistica", "Pistol", 1.05],
  ["Pox", "Pistol", 1.05],
  ["Arca Scisco", "Pistol", 1],
  ["Detron", "Pistol", 1],
  ["Gaze", "Kitgun", 1],
  ["Spira", "Pistol", 1],
  ["Twin Grakatas", "Pistol", 1],
  ["Hikou", "Pistol", 0.95],
  ["Pandero", "Pistol", 0.95],
  ["Rattleguts", "Kitgun", 0.9],
  ["Aklex", "Pistol", 0.85],
  ["Tombfinger", "Kitgun", 0.85],
  ["Akbolto", "Pistol", 0.8],
  ["Atomos", "Pistol", 0.8],
  ["Catchmoon", "Kitgun", 0.8],
  ["Gammacor", "Pistol", 0.8],
  ["Marelok", "Pistol", 0.8],
  ["Pyrana", "Pistol", 0.8],
  ["Sonicor", "Pistol", 0.8],
  ["Euphona Prime", "Pistol", 0.7],
  ["Lex", "Pistol", 0.7],
  ["Staticor", "Pistol", 0.53],
  ["Akstiletto", "Pistol", 0.5],

  // 近战 Melee
  ["Amphis", "Melee", 1.5],
  ["Ether Daggers", "Melee", 1.49],
  ["Cronus", "Melee", 1.48],
  ["Dark Sword", "Melee", 1.48],
  ["Dual Keres", "Melee", 1.48],
  ["Dual Skana", "Melee", 1.48],
  ["Heat Sword", "Melee", 1.48],
  ["Plasma Sword", "Melee", 1.48],
  ["Twin Krohkur", "Melee", 1.48],
  ["Jaw Sword", "Melee", 1.47],
  ["Kama", "Melee", 1.47],
  ["Pangolin Sword", "Melee", 1.47],
  ["Anku", "Melee", 1.46],
  ["Kogake", "Melee", 1.46],
  ["Ankyros", "Melee", 1.45],
  ["Dual Ether", "Melee", 1.45],
  ["Ether Reaper", "Melee", 1.45],
  ["Kestrel", "Melee", 1.45],
  ["Machete", "Melee", 1.45],
  ["Dual Heat Swords", "Melee", 1.44],
  ["Dual Zoren", "Melee", 1.44],
  ["Ether Sword", "Melee", 1.44],
  ["Gram", "Melee", 1.44],
  ["Halikar", "Melee", 1.44],
  ["Heat Dagger", "Melee", 1.44],
  ["Ceramic Dagger", "Melee", 1.43],
  ["Kronen", "Melee", 1.43],
  ["Mire", "Melee", 1.43],
  ["Nami Solo", "Melee", 1.43],
  ["Ninkondi", "Melee", 1.41],
  ["Dual Raza", "Melee", 1.4],
  ["Tekko", "Melee", 1.4],
  ["Furax", "Melee", 1.38],
  ["Ripkas", "Melee", 1.38],
  ["Serro", "Melee", 1.38],
  ["Tonbo", "Melee", 1.38],
  ["Cerata", "Melee", 1.36],
  ["Fang", "Melee", 1.36],
  ["Hate", "Melee", 1.36],
  ["Dragon Nikana", "Melee", 1.35],
  ["Gazal Machete", "Melee", 1.35],
  ["Shaku", "Melee", 1.35],
  ["Sibear", "Melee", 1.35],
  ["Lacera", "Melee", 1.31],
  ["Okina", "Melee", 1.31],
  ["Tipedo", "Melee", 1.31],
  ["Caustacyst", "Melee", 1.3],
  ["Scoliac", "Melee", 1.3],
  ["Bo", "Melee", 1.29],
  ["Karyst", "Melee", 1.29],
  ["Prova", "Melee", 1.29],
  ["Reaper Prime", "Melee", 1.29],
  ["Deconstructor", "Melee", 1.25],
  ["Sheev", "Melee", 1.25],
  ["Kesheg", "Melee", 1.24],
  ["Sarpa", "Melee", 1.24],
  ["Glaive", "Melee", 1.22],
  ["Krohkur", "Melee", 1.22],
  ["Skana", "Melee", 1.22],
  ["Dark Split-Sword", "Melee", 1.21],
  ["Volnus", "Melee", 1.2],
  ["Broken Scepter", "Melee", 1.19],
  ["Twin Basolk", "Melee", 1.18],
  ["Nami Skyla", "Melee", 1.175],
  ["Redeemer", "Melee", 1.17],
  ["Dual Ichor", "Melee", 1.16],
  ["Dakra Prime", "Melee", 1.15],
  ["Dex Dakra", "Melee", 1.15],
  ["Orvius", "Melee", 1.15],
  ["Destreza", "Melee", 1.14],
  ["Obex", "Melee", 1.1],
  ["Magistar", "Melee", 1.09],
  ["Arca Titron", "Melee", 1],
  ["Balla", "Zaw", 1],
  ["Boltace", "Melee", 1],
  ["Cassowar", "Melee", 1],
  ["Cobra & Crane", "Melee", 1],
  ["Cyath", "Zaw", 1],
  ["Dehtat", "Zaw", 1],
  ["Dokrahm", "Zaw", 1],
  ["Dual Cleavers", "Melee", 1],
  ["Endura", "Melee", 1],
  ["Falcor", "Melee", 1],
  ["Galvacord", "Melee", 1],
  ["Guandao", "Melee", 1],
  ["Gunsen", "Melee", 1],
  ["Korrudo", "Melee", 1],
  ["Kreska", "Melee", 1],
  ["Kronsh", "Zaw", 1],
  ["Mewan", "Zaw", 1],
  ["Ohma", "Melee", 1],
  ["Ooltha", "Zaw", 1],
  ["Paracesis", "Melee", 1],
  ["Plague Keewar", "Zaw", 1],
  ["Plague Kripath", "Zaw", 1],
  ["Pupacyst", "Melee", 1],
  ["Rabvee", "Zaw", 1],
  ["Scindo", "Melee", 1],
  ["Sepfahn", "Zaw", 1],
  ["Sigma & Octantis", "Melee", 1],
  ["Silva & Aegis", "Melee", 1],
  ["Skiajati", "Melee", 1],
  ["Tatsu", "Melee", 1],
  ["Fragor", "Melee", 0.96],
  ["Mios", "Melee", 0.95],
  ["Heliocor", "Melee", 0.94],
  ["Ack & Brunt", "Melee", 0.9],
  ["Sydon", "Melee", 0.84],
  ["Dual Kamas", "Melee", 0.81],
  ["Jat Kusar", "Melee", 0.81],
  ["Broken War", "Melee", 0.79],
  ["Jat Kittag", "Melee", 0.75],
  ["Dark Dagger", "Melee", 0.52],
  ["Atterax", "Melee", 0.5],
  ["Galatine", "Melee", 0.5],
  ["Hirudo", "Melee", 0.5],
  ["Lecta", "Melee", 0.5],
  ["Lesion", "Melee", 0.5],
  ["Nikana", "Melee", 0.5],
  ["Orthos", "Melee", 0.5],
  ["Venka", "Melee", 0.5],
  ["War", "Melee", 0.5],
  ["Zenistar", "Melee", 0.5],

  // 技能武器 Exalted Weapon
  ["Regulators", "Pistol", 0],
  ["Iron Staff", "Melee", 0],
  ["Valkyr Talons", "Melee", 0],
  ["Exalted Blade", "Melee", 0],
  ["Diwata", "Melee", 0],
  ["Artemis Bow", "Rifle", 0],
  ["Dex Pixia", "Pistol", 0],
  ["Whipclaw", "Melee", 0],
  ["Shattered Lash", "Melee", 0],
  ["Desert Wind", "Melee", 0],
  ["Landslide", "Melee", 0],
  ["Balefire", "Pistol", 0],

  // Archgun
  ["Cyngas", "Archgun", 1.4],
  ["Dual Decurion", "Archgun", 1.3],
  ["Phaedra", "Archgun", 1.15],
  ["Corvas", "Archgun", 1.05],
  ["Larkspur", "Archgun", 1],
  ["Velocitus", "Archgun", 0.95],
  ["Grattler", "Archgun", 0.9],
  ["Fluctus", "Archgun", 0.75],
  ["Imperator", "Archgun", 0.7],
  // Archmelee
  // ["Agkuza", "Archmelee", 1],
  // ["Centaur", "Archmelee", 1],
  // ["Kaszas", "Archmelee", 1],
  // ["Knux", "Archmelee", 1],
  // ["Onorix", "Archmelee", 1],
  // ["Rathbone", "Archmelee", 1],
  // ["Veritux", "Archmelee", 1],
  // Amp
  ["Amp", "Amp", 0]
] as [string, string, number][];

// 国服老版本的倾向数据
export const _rivenDataBaseWeaponsCY = [
  // 步枪 Rifle
  ["Miter", "Rifle", 1.6],
  ["Panthera", "Rifle", 1.55],
  ["Flux Rifle", "Rifle", 1.55],
  ["Harpak", "Rifle", 1.55],
  ["Mutalist Quanta", "Rifle", 1.55],
  ["Buzlok", "Rifle", 1.55],
  ["Tetra", "Rifle", 1.5],
  ["Phage", "Shotgun", 1.46],
  ["Deth Machine Rifle", "Rifle", 1.46],
  ["Hind", "Rifle", 1.42],
  ["Attica", "Rifle", 1.42],
  ["Tiberon", "Rifle", 1.4],
  ["Vulkar", "Rifle", 1.38],
  ["Glaxion", "Rifle", 1.35],
  ["Stinger", "Rifle", 1.31],
  ["Paracyst", "Rifle", 1.31],
  ["Karak", "Rifle", 1.28],
  ["Grinlok", "Rifle", 1.25],
  ["Dera", "Rifle", 1.25],
  ["Ogris", "Rifle", 1.25],
  ["Stradavar", "Rifle", 1.25],
  ["Synapse", "Rifle", 1.31],
  ["Vulklok", "Rifle", 1.25],
  ["Laser Rifle", "Rifle", 1.21],
  ["Opticor", "Rifle", 1.21],
  ["Mutalist Cernos", "Rifle", 1.21],
  ["Daikyu", "Rifle", 1.21],
  ["Quartakk", "Rifle", 1.2],
  ["Penta", "Rifle", 1.18],
  ["Gorgon", "Rifle", 1.18],
  ["Burston", "Rifle", 1.175],
  ["Snipetron", "Rifle", 1.165],
  ["Supra", "Rifle", 1.14],
  ["Torid", "Rifle", 1.14],
  ["Rubico", "Rifle", 1.105],
  ["Lanka", "Rifle", 1.105],
  ["Grakata", "Rifle", 1.1],
  ["Baza", "Rifle", 1.1],
  ["Zhuge", "Rifle", 1.1],
  ["Latron", "Rifle", 1.07],
  ["Javlok", "Rifle", 1],
  ["Tenora", "Rifle", 1],
  ["Zenith", "Rifle", 1],
  ["Ferrox", "Rifle", 1],
  ["Veldt", "Rifle", 1],
  ["Scourge", "Rifle", 1],
  ["Hema", "Rifle", 1],
  ["Argonak", "Rifle", 1],
  ["Vectis", "Rifle", 1],
  ["Artax", "Rifle", 1],
  ["Zarr", "Rifle", 1],
  ["Amprex", "Rifle", 0.965],
  ["Braton", "Rifle", 0.96],
  ["Paris", "Rifle", 0.96],
  ["Quanta", "Rifle", 0.9],
  ["Lenz", "Rifle", 0.9],
  ["Cernos", "Rifle", 0.86],
  ["Sybaris", "Rifle", 0.9],
  ["Dread", "Rifle", 0.82],
  ["Boltor", "Rifle", 0.79],
  ["Ignis", "Rifle", 0.79],
  ["Tonkor", "Rifle", 0.55],
  ["Simulor", "Rifle", 0.5],
  ["Soma", "Rifle", 0.5],
  // 霰弹枪 Shotgun
  ["Drakgoon", "Shotgun", 1.48],
  ["Convectrix", "Shotgun", 1.46],
  ["Strun", "Shotgun", 1.4],
  ["Kohm", "Shotgun", 1.4],
  ["Boar", "Shotgun", 1.34],
  ["Sobek", "Shotgun", 1.33],
  ["Astilla", "Shotgun", 1.2],
  ["Sweeper", "Shotgun", 1],
  ["Corinth", "Shotgun", 1],
  ["Phantasma", "Shotgun", 1],
  ["Arca Plasmor", "Shotgun", 0.9],
  ["Hek", "Shotgun", 0.55],
  ["Tigris", "Shotgun", 0.5],
  // 手枪 Pistol
  ["Vasto", "Pistol", 1.53],
  ["Kraken", "Pistol", 1.53],
  ["Magnus", "Pistol", 1.53],
  ["Viper", "Pistol", 1.53],
  ["Aklato", "Pistol", 1.52],
  ["Akzani", "Pistol", 1.52],
  ["Cestra", "Pistol", 1.52],
  ["Bolto", "Pistol", 1.51],
  ["Tysis", "Pistol", 1.51],
  ["Lato", "Pistol", 1.51],
  ["Kunai", "Pistol", 1.51],
  ["Seer", "Pistol", 1.5],
  ["Twin Gremlins", "Pistol", 1.5],
  ["Spectra", "Pistol", 1.49],
  ["Stug", "Pistol", 1.48],
  ["Nukor", "Pistol", 1.45],
  ["Embolist", "Pistol", 1.45],
  ["Burst Laser", "Pistol", 1.45],
  ["Talons", "Pistol", 1.44],
  ["Akjagara", "Pistol", 1.43],
  ["Castanas", "Pistol", 1.42],
  ["Twin Vipers", "Pistol", 1.41],
  ["Angstrum", "Pistol", 1.4],
  ["Sicarus", "Pistol", 1.4],
  ["Afuris", "Pistol", 1.39],
  ["Furis", "Pistol", 1.35],
  ["Dual Cestra", "Pistol", 1.35],
  ["Azima", "Pistol", 1.35],
  ["Acrid", "Pistol", 1.33],
  ["Akmagnus", "Pistol", 1.28],
  ["Aksomati", "Pistol", 1.26],
  ["Stubba", "Pistol", 1.25],
  ["Despair", "Pistol", 1.24],
  ["Fusilai", "Pistol", 1.2],
  ["Kohmak", "Pistol", 1.2],
  ["Bronco", "Pistol", 1.2],
  ["Akbronco", "Pistol", 1.2],
  ["Dual Toxocyst", "Pistol", 1.19],
  ["Akvasto", "Pistol", 1.15],
  ["Pyrana", "Pistol", 1.1],
  ["Kulstar", "Pistol", 1.1],
  ["Twin Kohmak", "Pistol", 1.1],
  ["Twin Rogga", "Pistol", 1],
  ["Pandero", "Pistol", 1],
  ["Zakti", "Pistol", 1],
  ["Hystrix", "Pistol", 1],
  ["Knell", "Pistol", 1],
  ["Arca Scisco", "Pistol", 1],
  ["Cycron", "Pistol", 1],
  ["Detron", "Pistol", 1],
  ["Aklex", "Pistol", 1],
  ["Zylok", "Pistol", 1],

  ["Gaze", "Kitgun", 1],
  ["Rattleguts", "Kitgun", 1],
  ["Tombfinger", "Kitgun", 1],
  ["Catchmoon", "Kitgun", 1],

  ["Atomos", "Pistol", 0.87],
  ["Akbolto", "Pistol", 0.85],
  ["Ballistica", "Pistol", 0.85],
  ["Pox", "Pistol", 0.82],
  ["Twin Grakatas", "Pistol", 0.76],
  ["Brakk", "Pistol", 0.75],
  ["Hikou", "Pistol", 0.69],
  ["Euphona Prime", "Pistol", 0.69],
  ["Spira", "Pistol", 0.66],
  ["Gammacor", "Pistol", 0.53],
  ["Staticor", "Pistol", 0.53],
  ["Marelok", "Pistol", 0.5],
  ["Akstiletto", "Pistol", 0.5],
  ["Lex", "Pistol", 0.5],
  ["Sonicor", "Pistol", 0.5],

  // 近战 Melee
  ["Amphis", "Melee", 1.5],
  ["Ether Daggers", "Melee", 1.49],
  ["Cronus", "Melee", 1.48],
  ["Dark Sword", "Melee", 1.48],
  ["Dual Keres", "Melee", 1.48],
  ["Dual Skana", "Melee", 1.48],
  ["Heat Sword", "Melee", 1.48],
  ["Plasma Sword", "Melee", 1.48],
  ["Twin Krohkur", "Melee", 1.48],
  ["Jaw Sword", "Melee", 1.47],
  ["Kama", "Melee", 1.47],
  ["Pangolin Sword", "Melee", 1.47],
  ["Anku", "Melee", 1.46],
  ["Kogake", "Melee", 1.46],
  ["Ankyros", "Melee", 1.45],
  ["Dual Ether", "Melee", 1.45],
  ["Ether Reaper", "Melee", 1.45],
  ["Kestrel", "Melee", 1.45],
  ["Machete", "Melee", 1.45],
  ["Dual Heat Swords", "Melee", 1.44],
  ["Dual Zoren", "Melee", 1.44],
  ["Ether Sword", "Melee", 1.44],
  ["Gram", "Melee", 1.44],
  ["Halikar", "Melee", 1.44],
  ["Heat Dagger", "Melee", 1.44],
  ["Ceramic Dagger", "Melee", 1.43],
  ["Kronen", "Melee", 1.43],
  ["Mire", "Melee", 1.43],
  ["Nami Solo", "Melee", 1.43],
  ["Ninkondi", "Melee", 1.41],
  ["Dual Raza", "Melee", 1.4],
  ["Tekko", "Melee", 1.4],
  ["Furax", "Melee", 1.38],
  ["Ripkas", "Melee", 1.38],
  ["Serro", "Melee", 1.38],
  ["Tonbo", "Melee", 1.38],
  ["Cerata", "Melee", 1.36],
  ["Fang", "Melee", 1.36],
  ["Hate", "Melee", 1.36],
  ["Dragon Nikana", "Melee", 1.35],
  ["Gazal Machete", "Melee", 1.35],
  ["Shaku", "Melee", 1.35],
  ["Sibear", "Melee", 1.35],
  ["Lacera", "Melee", 1.31],
  ["Okina", "Melee", 1.31],
  ["Tipedo", "Melee", 1.31],
  ["Caustacyst", "Melee", 1.3],
  ["Scoliac", "Melee", 1.3],
  ["Bo", "Melee", 1.29],
  ["Karyst", "Melee", 1.29],
  ["Prova", "Melee", 1.29],
  ["Reaper Prime", "Melee", 1.29],
  ["Deconstructor", "Melee", 1.25],
  ["Sheev", "Melee", 1.25],
  ["Kesheg", "Melee", 1.24],
  ["Sarpa", "Melee", 1.24],
  ["Glaive", "Melee", 1.22],
  ["Krohkur", "Melee", 1.22],
  ["Skana", "Melee", 1.22],
  ["Dark Split-Sword", "Melee", 1.21],
  ["Volnus", "Melee", 1.2],
  ["Broken Scepter", "Melee", 1.19],
  ["Twin Basolk", "Melee", 1.18],
  ["Nami Skyla", "Melee", 1.175],
  ["Redeemer", "Melee", 1.17],
  ["Dual Ichor", "Melee", 1.16],
  ["Dakra Prime", "Melee", 1.15],
  ["Dex Dakra", "Melee", 1.15],
  ["Orvius", "Melee", 1.15],
  ["Destreza", "Melee", 1.14],
  ["Obex", "Melee", 1.1],
  ["Magistar", "Melee", 1.09],
  ["Arca Titron", "Melee", 1],
  ["Balla", "Zaw", 1],
  ["Boltace", "Melee", 1],
  ["Cassowar", "Melee", 1],
  ["Cobra & Crane", "Melee", 1],
  ["Cyath", "Zaw", 1],
  ["Dehtat", "Zaw", 1],
  ["Dokrahm", "Zaw", 1],
  ["Dual Cleavers", "Melee", 1],
  ["Endura", "Melee", 1],
  ["Falcor", "Melee", 1],
  ["Galvacord", "Melee", 1],
  ["Guandao", "Melee", 1],
  ["Gunsen", "Melee", 1],
  ["Korrudo", "Melee", 1],
  ["Kreska", "Melee", 1],
  ["Kronsh", "Zaw", 1],
  ["Mewan", "Zaw", 1],
  ["Ohma", "Melee", 1],
  ["Ooltha", "Zaw", 1],
  ["Paracesis", "Melee", 1],
  ["Plague Keewar", "Zaw", 1],
  ["Plague Kripath", "Zaw", 1],
  ["Pupacyst", "Melee", 1],
  ["Rabvee", "Zaw", 1],
  ["Scindo", "Melee", 1],
  ["Sepfahn", "Zaw", 1],
  ["Sigma & Octantis", "Melee", 1],
  ["Silva & Aegis", "Melee", 1],
  ["Skiajati", "Melee", 1],
  ["Tatsu", "Melee", 1],
  ["Fragor", "Melee", 0.96],
  ["Mios", "Melee", 0.95],
  ["Heliocor", "Melee", 0.94],
  ["Ack & Brunt", "Melee", 0.9],
  ["Sydon", "Melee", 0.84],
  ["Dual Kamas", "Melee", 0.81],
  ["Jat Kusar", "Melee", 0.81],
  ["Broken War", "Melee", 0.79],
  ["Jat Kittag", "Melee", 0.75],
  ["Dark Dagger", "Melee", 0.52],
  ["Atterax", "Melee", 0.5],
  ["Galatine", "Melee", 0.5],
  ["Hirudo", "Melee", 0.5],
  ["Lecta", "Melee", 0.5],
  ["Lesion", "Melee", 0.5],
  ["Nikana", "Melee", 0.5],
  ["Orthos", "Melee", 0.5],
  ["Venka", "Melee", 0.5],
  ["War", "Melee", 0.5],
  ["Zenistar", "Melee", 0.5],

  // 技能武器 Exalted Weapon
  ["Regulators", "Pistol", 0],
  ["Iron Staff", "Melee", 0],
  ["Valkyr Talons", "Melee", 0],
  ["Exalted Blade", "Melee", 0],
  ["Diwata", "Melee", 0],
  ["Artemis Bow", "Rifle", 0],
  ["Dex Pixia", "Pistol", 0],
  ["Whipclaw", "Melee", 0],
  ["Shattered Lash", "Melee", 0],
  ["Desert Wind", "Melee", 0],
  ["Landslide", "Melee", 0],
  ["Balefire", "Pistol", 0],

  // Archgun
  ["Cyngas", "Archgun", 1.4],
  ["Dual Decurion", "Archgun", 1.3],
  ["Phaedra", "Archgun", 1.15],
  ["Corvas", "Archgun", 1.05],
  ["Larkspur", "Archgun", 1],
  ["Velocitus", "Archgun", 0.95],
  ["Grattler", "Archgun", 0.9],
  ["Fluctus", "Archgun", 0.75],
  ["Imperator", "Archgun", 0.7],

  // Archmelee
  // ["Agkuza", "Archmelee", 0],
  // ["Centaur", "Archmelee", 0],
  // ["Kaszas", "Archmelee", 0],
  // ["Knux", "Archmelee", 0],
  // ["Onorix", "Archmelee", 0],
  // ["Rathbone", "Archmelee", 0],
  // ["Veritux", "Archmelee", 0],

  // Amp
  ["Amp", "Amp", 0]
] as [string, string, number][];
