exports = [
{id:"Burst Laser",name:"burstLaser",rivenName:"Burst Laser",tags:["Gun","Robotic","Pistol"],dmg:[["Puncture",6],["Slash",0.3],["Impact",0.7]],critMul:1.3,critChance:0.025,fireRate:1.5,status:0.02,accuracy:100,magazine:15,reload:0},
{id:"Prisma Burst Laser",name:"prismaBurstLaser",rivenName:"Burst Laser",tags:["Gun","Robotic","Pistol"],dmg:[["Puncture",8.5],["Slash",0.5],["Impact",1]],critMul:2,critChance:0.05,fireRate:1.61,status:0.1,accuracy:100,magazine:15,reload:0},
{id:"Vulklok",name:"vulklok",rivenName:"Vulklok",tags:["Gun","Robotic","Sniper Rifle"],dmg:[["Electricity",85]],critMul:2.5,critChance:0.35,fireRate:0.15,status:0.25,accuracy:100,magazine:10,reload:2},
{id:"Artax",name:"artax",rivenName:"Artax",tags:["Gun","Robotic","Rifle"],dmg:[["Cold",5]],critMul:1.5,critChance:0.02,fireRate:1,status:0.03,accuracy:12.5,magazine:100,reload:1.5},
{id:"Vulcax",name:"vulcax",rivenName:"Vulcax",tags:["Gun","Robotic","Rifle"],dmg:[["Heat",35]],critMul:2.5,critChance:0.2,fireRate:1,status:0.1,accuracy:100,magazine:1,reload:6},
{id:"Sweeper Prime",name:"sweeperPrime",rivenName:"Sweeper",tags:["Gun","Robotic","Shotgun"],dmg:[["Puncture",3],["Slash",6],["Impact",51]],critMul:2,critChance:0.05,fireRate:1,status:0.15,accuracy:3.3,bullets:6,magazine:20,reload:2},
{id:"Sweeper",name:"sweeper",rivenName:"Sweeper",tags:["Gun","Robotic","Shotgun"],dmg:[["Puncture",2.1],["Slash",4.2],["Impact",35.7]],critMul:1.5,critChance:0.05,fireRate:1,status:0.14,accuracy:3.3,bullets:6,magazine:10,reload:2.3},
{id:"Stinger",name:"stinger",rivenName:"Stinger",tags:["Gun","Robotic","Rifle"],dmg:[["Toxin",15]],critMul:1.5,critChance:0.025,fireRate:3.3,status:0.05,accuracy:100,magazine:4,reload:1.2},
{id:"Prime Laser Rifle",name:"primeLaserRifle",rivenName:"Laser Rifle",tags:["Gun","Robotic","Rifle"],dmg:[["Puncture",8.4],["Slash",2.4],["Impact",1.2]],critMul:1.5,critChance:0.15,fireRate:10,status:0.05,accuracy:100,magazine:5,reload:1.2},
{id:"Multron",name:"multron",rivenName:"Multron",tags:["Gun","Robotic","Rifle"],dmg:[["Puncture",3.8],["Impact",1.3]],critMul:1.8,critChance:0.125,fireRate:3.33,status:0.05,accuracy:18.2,magazine:60,reload:3},
{id:"Laser Rifle",name:"laserRifle",rivenName:"Laser Rifle",tags:["Gun","Robotic","Rifle"],dmg:[["Puncture",6.4],["Slash",0.8],["Impact",0.8]],critMul:1.3,critChance:0.025,fireRate:6.7,status:0.02,accuracy:100,magazine:5,reload:1.2},
{id:"Deconstructor Prime",name:"deconstructorPrime",rivenName:"Deconstructor",tags:["Gun","Robotic","Glaive"],dmg:[["Impact",75]],critChance:0,fireRate:1.33,status:0.25,accuracy:100,magazine:6,reload:3},
{id:"Deth Machine Rifle",name:"dethMachineRifle",rivenName:"Deth Machine Rifle",tags:["Gun","Robotic","Rifle"],dmg:[["Puncture",0.3],["Slash",4.3],["Impact",0.5]],critMul:2,critChance:0.05,fireRate:8.3,status:0.01,accuracy:100,magazine:100,reload:2},
{id:"Cryotra",name:"cryotra",rivenName:"Cryotra",tags:["Gun","Robotic","Rifle"],dmg:[["Cold",10]],critMul:2,critChance:0.05,fireRate:1,status:0.35,accuracy:12.5,magazine:80,reload:4},
{id:"Tazicor",name:"tazicor",rivenName:"Tazicor",tags:["Gun","Robotic","Rifle"],dmg:[["Electricity",6]],critMul:1.5,critChance:0.02,fireRate:8.33,status:0.15,accuracy:25,magazine:4,reload:2.5},
{id:"Deconstructor",name:"deconstructor",rivenName:"Deconstructor",tags:["Gun","Robotic","Glaive"],dmg:[["Impact",50]],critChance:0,fireRate:1.3,status:0.25,accuracy:100,magazine:6,reload:3}
]